config/routes.rb
Rails.application.routes.draw do
  root 'newsletter#sign_up'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'newsletter/sign_up/(:id)', to: 'newsletter#sign_up'
  post 'newsletter/sign_up/(:id)', to: 'newsletter#submit'
  get 'newsletter/success/(:id)', to: 'newsletter#success'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  #Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/email_validatable.rb
require 'mail'

module EmailValidatable
  extend ActiveSupport::Concern

  class EmailValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      begin
        a = Mail::Address.new(value)
      rescue Mail::Field::ParseError
        record.errors[attribute] << (options[:message] || "is not an email")
      end
    end
  end
end

app/models/referral.rb
class Referral < ApplicationRecord
  belongs_to :user, foreign_key: :referrer, foreign_key: :referred

end

app/models/user.rb
class User < ApplicationRecord
  has_many :referrals, counter_cache: :count_of_referrals
  devise :registerable, :trackable #record ip address upon sign in
  #email verification
  validates :email, uniqueness: true, format: { with: Devise::email_regexp, message: "Invalid email format." }, presence: true
  validates :current_sign_in_ip, uniqueness: true #validates that ip address is new
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController

  def sign_up #allows for user to sign up and records their id and ip
    @user = User.new
    @id = params[:id]
    @ip = params[:current_sign_in_ip]
  end

  def submit
    email = params[:user][:email]
    @user = User.new(email: email, counter: 0)

    if @user.save || params[:current_sign_in_ip] #check to see if already current user
      cookies[:id] = @user.id

      if params[:id]
        @referral = Referral.new(referrer: params[:id], referred: @user.id)
        @referral.save!

        #Update referrer's counter
        @referrer_user = User.find(params[:id])
        @referrer_user.update(counter: @referrer_user.counter+1)
      end

      #Directs to success page
      redirect_to "/newsletter/success/#{@user.id}"

    else
      logger.info("Error saving user with email, #{email}")
      redirect_to root_path, alert: 'Something went wrong!'
    end
  end

  def success
  end

  def check_session
    if cookies[:id] && User.where(id: cookies[:id]).any? && !admin_user
      redirect_to "/newsletter/success/#{@user.id}"
    end
  end

  def progress
    User.find(params[:id]).each do
      @user.counter
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletter_helper.rb
module NewsletterHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Refnew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/newsletter/sign_up.html.erb
<!DOCTYPE html>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

<html lang="en">

  <p id="notice"><%= notice %></p>
  <head>
      <style>
        body {
          background: url('') no-repeat center center fixed;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          background-size: cover;
          -o-background-size: cover;
          background-color: white;

            font-family: 'Lato', 'Helvetica Neue', Helvetica, Arial, sans-serif;
          }

          h1,
          h2,
          h3,
          h4,
          h5,
          h6 {
            font-family: 'Lato', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-weight: 700;

        }

        body::after {
          content: "";
          background: url("https://github.com/olivianye1/ROTSee/blob/master/app/views/cadets/ROTSee2.jpg?raw=true");
          opacity: 0.2;
          top: 0;
          left: 0;
          bottom: 0;
          right: 0;
          position: absolute;
          z-index: -1;
}

        /* Container holding the image and the text */
        .container {
          position: relative;
          text-align: center;
          color: black;
        }

        /* Centered text */
        .centered {
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
        }

        .front-page {

          margin-bottom: 25px;
        }

        .features-icons {
          padding-top: 7rem;
          padding-bottom: 7rem;
        }

        .features-icons .features-icons-item {
          max-width: 20rem;
        }

        .features-icons .features-icons-item .features-icons-icon {
          height: 7rem;
        }

        .features-icons .features-icons-item .features-icons-icon i {
          font-size: 4.5rem;
        }

        .features-icons .features-icons-item:hover .features-icons-icon i {
          font-size: 5rem;
        }

        header.masthead {
          position: relative;
          background: url("https://raw.githubusercontent.com/BlackrockDigital/startbootstrap-landing-page/master/img/bg-masthead.jpg") no-repeat center center;
          background-color: #343a40;
          background-size: cover;
          padding-top: 8rem;
          padding-bottom: 8rem;
        }

        header.masthead .overlay {
          position: absolute;
          background-color: #212529;
          height: 100%;
          width: 100%;
          top: 0;
          left: 0;
          opacity: 0.3;
        }

        header.masthead h1 {
          font-size: 2rem;
        }

        @media (min-width: 768px) {
          header.masthead {
            padding-top: 12rem;
            padding-bottom: 12rem;
          }
          header.masthead h1 {
            font-size: 3rem;
          }
        }

        footer.footer {
          padding-top: 4rem;
          padding-bottom: 4rem;
        }
      </style>
  </head>
  <header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">Track Referrals. Watch Your Business Grow.</h1>
        </div>
        <div class="col-xl-9 mx-auto">
          <%= form_with(model: @user, local: true, url: "/newsletter/sign_up/#{@id}") do |form| %>
            <%= render 'shared/error_messages' %>
              <%= form.text_field :email, :placeholder => "Enter Email"%>
              <%= form.submit "Step Inside!"%>
            <% end %>
        </div>
      </div>
    </div>
  </header>

  <section class="features-icons bg-light text-center">
    <div class = "container">
      <div class="row">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="fa fa-users m-auto text-primary"></i>
            </div>
            <h3>Viral Growth</h3>
            <p class="lead mb-0">All you need to get started.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="fa fa-check-square m-auto text-primary"></i>
            </div>
            <h3>Admin Dashboard</h3>
            <p class="lead mb-0">Track word of mouth.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="fa fa-angle-double-up m-auto text-primary"></i>
            </div>
            <h3>Easy to Use</h3>
            <p class="lead mb-0">Launch your campaign easily.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <footer>
    <a href="https://github.com/ilanaseidl/refnew" style="font-sizeM 24px;">Learn more.</a>
    <br>
    <br>
  </footer>


</html>

app/views/newsletter/success.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

  .carousel-inner img {
      width: 80%; /* Set width to 80% */
      margin: auto;
      min-height:200px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }
  }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="#">Admin</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="https://placehold.it/1200x400?text=IMAGE" alt="Image">
        <div class="carousel-caption">
          <h3>Share this link to win rewards:</h3>
          <p><%= "http://refnew.herokupp.com/newsletter/sign_up/#{params[:id]}" %></p>
        </div>
      </div>

  <p id="notice"><%= notice %></p>
  <head>
      <style>
        body {
          background: url('') no-repeat center center fixed;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          background-size: cover;
          -o-background-size: cover;
          background-color: white;

            font-family: 'Lato', 'Helvetica Neue', Helvetica, Arial, sans-serif;
          }

          h1,
          h2,
          h3,
          h4,
          h5,
          h6 {
            font-family: 'Lato', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-weight: 700;

        }

        body::after {
          content: "";
          background: url("https://github.com/olivianye1/ROTSee/blob/master/app/views/cadets/ROTSee2.jpg?raw=true");
          opacity: 0.2;
          top: 0;
          left: 0;
          bottom: 0;
          right: 0;
          position: absolute;
          z-index: -1;
}

        /* Container holding the image and the text */
        .container {
          position: relative;
          text-align: center;
          color: black;
        }

        /* Centered text */
        .centered {
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
        }

        .front-page {

          margin-bottom: 25px;
        }

        .features-icons {
          padding-top: 7rem;
          padding-bottom: 7rem;
        }

        .features-icons .features-icons-item {
          max-width: 20rem;
        }

        .features-icons .features-icons-item .features-icons-icon {
          height: 7rem;
        }

        .features-icons .features-icons-item .features-icons-icon i {
          font-size: 4.5rem;
        }

        .features-icons .features-icons-item:hover .features-icons-icon i {
          font-size: 5rem;
        }

        header.masthead {
          position: relative;
          background: url("https://raw.githubusercontent.com/BlackrockDigital/startbootstrap-landing-page/master/img/bg-masthead.jpg") no-repeat center center;
          background-color: #343a40;
          background-size: cover;
          padding-top: 8rem;
          padding-bottom: 8rem;
        }

        header.masthead .overlay {
          position: absolute;
          background-color: #212529;
          height: 100%;
          width: 100%;
          top: 0;
          left: 0;
          opacity: 0.3;
        }

        header.masthead h1 {
          font-size: 2rem;
        }

        @media (min-width: 768px) {
          header.masthead {
            padding-top: 12rem;
            padding-bottom: 12rem;
          }
          header.masthead h1 {
            font-size: 3rem;
          }
        }

        footer.footer {
          padding-top: 4rem;
          padding-bottom: 4rem;
        }
      </style>
  </head>
  <header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">Share with friends. Grow your rewards!</h1>
        </div>
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="input-group">
                <div data-controller="clipboard">
                <input class="form-control" value="<%= "http://refnew.herokupp.com/newsletter/sign_up/#{params[:id]}" %>" data-target="clipboard.source"</input>
                <span class="input-group-btn">
                  <button type="button" class="btn btn-default" data-action="clipboard#copy">Copy to Clipboard</button>
                </span>
            </div>
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h4 class="mb-5" style="color:white">Share your unique link via email or social networks and earn prizes for each friend who signs up!</h4>
            <div class="row">
              <div class="col-xl-9 mx-auto">
                <a href="http://facebook.com"><i class="fa fa-facebook m-auto" style="font-size: 210%;color: white;"></i>
                <a href="http://instagram.com"><i class="fa fa-instagram m-auto" style="font-size: 210%;color:white;"></i>
                <a href="http://twitter.com"><i class="fa fa-twitter m-auto" style="font-size: 210%;color: white;"></i>
              </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="features-icons bg-light text-center">
    <div class = "container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="d-flex justify-content-center">
          <h3 class="text-center">
            <h4>
              <strong>7 friends</strong>
            <span>have joined so far! Keep going.</span>
            </h4>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
      </div>
    </div>
  </div>
      <div class="row">
        <div class="d-flex justify-content-center">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="fa fa-gift m-auto text-primary"></i>
            </div>
            <h3>5</h3>
            <p class="lead mb-0">Prize 1</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">

              <i class="fa fa-gift m-auto text-primary"></i>
            </div>
            <h3>10</h3>
            <p class="lead mb-0">Prize 2</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="fa fa-gift m-auto text-primary"></i>
            </div>
            <h3>15</h3>
            <p class="lead mb-0">Prize 3</p>
          </div>
        </div>
      </div>
    </div>

  <section class ="footer">
    <a href="https://github.com/ilanaseidl/refnew" style="font-sizeM 24px;">Learn more.</a>
    <br>
    <br>
  </section>

<div class="progress" style="height: 40px">
  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="height: 40px; width: 35%" aria-valuenow="7" aria-valuemin="0" aria-valuemax="20"><span class="sr-only">7 Referrals</span>7 Referrals</div>
</div>

<footer class="container-fluid text-center">
  <p>Refer your friends!</p>
</footer>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %> %>
    <li> <%= msg %> </li>
    <% end %>
    </ul>
  </div>
<% end %>